// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:elearning_management_app/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnnouncementAdapter());
    registerAdapter(AssignmentAdapter());
    registerAdapter(AssignmentSubmissionAdapter());
    registerAdapter(CourseAdapter());
    registerAdapter(CourseMaterialAdapter());
    registerAdapter(GroupAdapter());
    registerAdapter(QuestionAdapter());
    registerAdapter(QuestionOptionAdapter());
    registerAdapter(QuizAdapter());
    registerAdapter(QuizAttemptAdapter());
    registerAdapter(SemesterAdapter());
    registerAdapter(StudentAdapter());
    registerAdapter(UserModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AnnouncementAdapter());
    registerAdapter(AssignmentAdapter());
    registerAdapter(AssignmentSubmissionAdapter());
    registerAdapter(CourseAdapter());
    registerAdapter(CourseMaterialAdapter());
    registerAdapter(GroupAdapter());
    registerAdapter(QuestionAdapter());
    registerAdapter(QuestionOptionAdapter());
    registerAdapter(QuizAdapter());
    registerAdapter(QuizAttemptAdapter());
    registerAdapter(SemesterAdapter());
    registerAdapter(StudentAdapter());
    registerAdapter(UserModelAdapter());
  }
}
